import { v4 } from 'uuid';

export const PRODUCTS = [
  {
    id: v4(),
    name: 'Waffle',
    title: 'Waffle with Berries',
    price: 6.5,
    imgMobile: '/assets/images/image-waffle-mobile.jpg',
    imgTablet: '/assets/images/image-waffle-tablet.jpg',
    imgDesktop: '/assets/images/image-waffle-desktop.jpg',
    imgThumbnail: '/assets/images/image-waffle-thumbnail.jpg',
    alt: 'A waffle tower with sliced strawberries and icing sugar.',
  },

  {
    id: v4(),
    name: 'Crème Brûlée',
    title: 'Vanilla Bean Crème Brûlée',
    price: 7.0,
    imgMobile: '/assets/images/image-creme-brulee-mobile.jpg',
    imgTablet: '/assets/images/image-creme-brulee-tablet.jpg',
    imgDesktop: '/assets/images/image-creme-brulee-desktop.jpg',
    imgThumbnail: '/assets/images/image-creme-brulee-thumbnail.jpg',
    alt: 'Two dishes of crème brûlée topped with berries, figs and mint.',
  },

  {
    id: v4(),
    name: 'Macaron',
    title: 'Macaron Mix of Five',
    price: 8.0,
    imgMobile: '/assets/images/image-macaron-mobile.jpg',
    imgTablet: '/assets/images/image-macaron-tablet.jpg',
    imgDesktop: '/assets/images/image-macaron-desktop.jpg',
    imgThumbnail: '/assets/images/image-macaron-thumbnail.jpg',
    alt: 'Five different flavour macarons.',
  },

  {
    id: v4(),
    name: 'Tiramisu',
    title: 'Classic Tiramisu',
    price: 5.5,
    imgMobile: '/assets/images/image-tiramisu-mobile.jpg',
    imgTablet: '/assets/images/image-tiramisu-tablet.jpg',
    imgDesktop: '/assets/images/image-tiramisu-desktop.jpg',
    imgThumbnail: '/assets/images/image-tiramisu-thumbnail.jpg',
    alt: 'A tiramisu topped with berries, mint and cocoa powder.',
  },

  {
    id: v4(),
    name: 'Baklava',
    title: 'Pistachio Baklava',
    price: 4.0,
    imgMobile: '/assets/images/image-baklava-mobile.jpg',
    imgTablet: '/assets/images/image-baklava-tablet.jpg',
    imgDesktop: '/assets/images/image-baklava-desktop.jpg',
    imgThumbnail: '/assets/images/image-baklava-thumbnail.jpg',
    alt: 'Three triangle-shaped baklavas topped with crushed pistachios.',
  },

  {
    id: v4(),
    name: 'Pie',
    title: 'Lemon Meringue Pie',
    price: 5.0,
    imgMobile: '/assets/images/image-meringue-mobile.jpg',
    imgTablet: '/assets/images/image-meringue-tablet.jpg',
    imgDesktop: '/assets/images/image-meringue-desktop.jpg',
    imgThumbnail: '/assets/images/image-meringue-thumbnail.jpg',
    alt: 'A slice of lemon pie coronated with meringue.',
  },

  {
    id: v4(),
    name: 'Cake',
    title: 'Red Velvet Cake',
    price: 4.5,
    imgMobile: '/assets/images/image-cake-mobile.jpg',
    imgTablet: '/assets/images/image-cake-tablet.jpg',
    imgDesktop: '/assets/images/image-cake-desktop.jpg',
    imgThumbnail: '/assets/images/image-cake-thumbnail.jpg',
    alt: 'Red velvet cake portion with sliced strawberries on the inside and a berry on top.',
  },

  {
    id: v4(),
    name: 'Brownie',
    title: 'Salted Caramel Brownie',
    price: 5.5,
    imgMobile: '/assets/images/image-brownie-mobile.jpg',
    imgTablet: '/assets/images/image-brownie-tablet.jpg',
    imgDesktop: '/assets/images/image-brownie-desktop.jpg',
    imgThumbnail: '/assets/images/image-brownie-thumbnail.jpg',
    alt: 'A portion of brownie with vanilla ice cream and caramel syrup.',
  },

  {
    id: v4(),
    name: 'Cotta',
    title: 'Vanilla Panna Cotta',
    price: 6.5,
    imgMobile: '/assets/images/image-panna-cotta-mobile.jpg',
    imgTablet: '/assets/images/image-panna-cotta-tablet.jpg',
    imgDesktop: '/assets/images/image-panna-cotta-desktop.jpg',
    imgThumbnail: '/assets/images/image-panna-cotta-thumbnail.jpg',
    alt: 'Two crystal jars of panna cotta with cream.',
  },
];
